import type { DetailMovie } from "../types/DetailMovie";

export const movies: DetailMovie[] = [
  {
    id: 1,
    title: "Una nueva esperanza",
    longTitle: "Star Wars: Episodio IV - Una nueva esperanza",
    releaseDate: "25-05-1977",
    description:
      "Luke Skywalker comienza un viaje que cambiará la galaxia en Star Wars: Episodio IV - Una Nueva Esperanza. Diecinueve años después de la formación del Imperio, Luke es lanzado a la lucha de la Alianza Rebelde cuando conoce a Obi-Wan Kenobi, quien ha vivido durante años en reclusión en el planeta desértico de Tatooine. Obi-Wan comienza el entrenamiento Jedi de Luke mientras se une a él en una audaz misión para rescatar a la hermosa líder rebelde, la Princesa Leia, de las garras de Darth Vader y el malvado Imperio.",
    directedBy: "George Lucas",
    writtenBy: ["George Lucas"],
    era: "Año de la rebelión",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 1min",
    trailer: "https://www.youtube.com/embed/beAH5vea99k?si=LHfLoyDTy_ulfk3S",
  },
  {
    id: 2,
    title: "El Imperio contraataca",
    longTitle: "Star Wars: Episodio V - El Imperio contraataca",
    releaseDate: "17-05-1980",
    description:
      "Después de la destrucción de la Estrella de la Muerte, las fuerzas Imperiales continúan persiguiendo a los Rebeldes. Tras la derrota de la Rebelión en el planeta helado de Hoth, Luke emprende un viaje al planeta Dagobah para entrenar con el Maestro Jedi Yoda, quien ha vivido oculto desde la caída de la República. En un intento por convertir a Luke al lado oscuro, Darth Vader atrae al joven Skywalker hacia una trampa en la Ciudad de las Nubes de Bespin.",
    directedBy: "Irvin Kershner",
    writtenBy: ["Lawrence Kasdan ", "Leigh Brackett"],
    era: "Año de la rebelión",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 4min",
    trailer: "https://www.youtube.com/embed/xr3hPFJAHO4?si=FcgYnGFDKVe7HYGG",
  },
  {
    id: 3,
    title: "El retorno del Jedi",
    longTitle: "Star Wars. Episodio VI: El retorno del Jedi",
    releaseDate: "25-05-1983",
    description:
      "Después de un rápido viaje de regreso a Tatooine, Luke Skywalker, Leia Organa y Han Solo se reúnen y se unen a la creciente flota rebelde para derrotar de una vez por todas al malvado Imperio. Pero el Imperio también está tramando algo. El Emperador Palpatine comanda a sus tropas a bordo de su recién construida Estrella de la Muerte estacionada sobre la luna boscosa de Endor, donde los rebeldes, junto con algunos amigos peludos poco probables, hacen frente al Imperio. Mientras Luke Skywalker confronta una vez más a Darth Vader en la Estrella de la Muerte, Han lidera un equipo para desactivar un escudo que protege la estación de batalla para que la flota rebelde pueda destruirla una vez más y finalmente poner fin a la guerra...",
    directedBy: "Richard Marquand",
    writtenBy: ["Lawrence Kasdan", "George Lucas"],
    era: "Año de la rebelión",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 14min",
    trailer: "https://www.youtube.com/embed/yhuKapE-Bio?si=HwaCisVdWsFZUdyq",
  },
  {
    id: 4,
    title: "La amenaza fantasma",
    longTitle: "Star Wars: Episodio I - La amenaza fantasma",
    releaseDate: "19-05-1999",
    description:
      "Experimenta la acción heroica y las aventuras inolvidables de Star Wars: Episodio I - La Amenaza Fantasma. Observa los primeros pasos fatídicos en el viaje de Anakin Skywalker. Varados en el planeta desértico Tatooine después de rescatar a la joven Reina Amidala de la inminente invasión de Naboo, el aprendiz Jedi Obi-Wan Kenobi y su Maestro Jedi Qui-Gon Jinn descubren a Anakin, un niño de nueve años que posee una inusual fuerza en la Fuerza. Anakin gana una emocionante Carrera de Pods y con ella su libertad mientras deja su hogar para ser entrenado como Jedi. Los héroes regresan a Naboo donde Anakin y la Reina enfrentan enormes fuerzas de invasión mientras los dos Jedi lidian con un enemigo mortal llamado Darth Maul. Solo entonces se dan cuenta de que la invasión es apenas el primer paso en un siniestro plan por parte de las fuerzas resurgentes de la oscuridad conocidas como los Sith.",
    directedBy: "George Lucas",
    writtenBy: ["George Lucas"],
    era: "Caida del Jedi",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 16min",
    trailer: "https://www.youtube.com/embed/KHwdeFuKjTU?si=2yv8tT8nLTiBin-K",
  },
  {
    id: 5,
    title: "El ataque de los clones",
    longTitle: "Star Wars: Episodio II - El ataque de los clones",
    releaseDate: "16-05-2002",
    description:
      "Observa cómo las semillas de la transformación de Anakin Skywalker echan raíces en Star Wars: Episodio II - El Ataque de los Clones. Diez años después de la invasión de Naboo, la galaxia está al borde de la guerra civil. Bajo el liderazgo de un Jedi renegado llamado Conde Dooku, miles de sistemas solares amenazan con separarse de la República Galáctica. Cuando se hace un intento de asesinato contra la Senadora Padmé Amidala, la ex Reina de Naboo, al joven aprendiz Jedi de veinte años, Anakin Skywalker, se le asigna protegerla. En el transcurso de su misión, Anakin descubre su amor por Padmé, así como su propio lado más oscuro. Pronto, Anakin, Padmé y Obi-Wan Kenobi son arrastrados al corazón del movimiento Separatista y al comienzo de las Guerras Clon.",
    directedBy: "George Lucas",
    writtenBy: ["George Lucas", "Jonathan Hales"],
    era: "Caida del Jedi",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 22min",
    trailer: "https://www.youtube.com/embed/DywnxIuPtUs?si=pTrLJAQ09TQv7oc1",
  },
  {
    id: 6,
    title: "La venganza de los Sith",
    longTitle: "Star Wars: Episodio III - La venganza de los Sith",
    releaseDate: "19-05-2005",
    description:
      "Descubre el verdadero poder del lado oscuro en Star Wars: Episodio III - La Venganza de los Sith. Años después del inicio de las Guerras Clon, los nobles Caballeros Jedi lideran un enorme ejército de clones en una batalla galáctica contra los Separatistas. Cuando los siniestros Sith desvelan un plan de mil años para gobernar la galaxia, la República se desmorona y de sus cenizas surge el malvado Imperio Galáctico. El héroe Jedi Anakin Skywalker es seducido por el lado oscuro de la Fuerza para convertirse en el nuevo aprendiz del Emperador, Darth Vader. Los Jedi son diezmados, mientras que Obi-Wan Kenobi y el Maestro Jedi Yoda son obligados a esconderse.",
    directedBy: "George Lucas",
    writtenBy: ["George Lucas"],
    era: "Caida del Jedi",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 20min",
    trailer: "https://www.youtube.com/embed/kqkfjBKmWc4?si=oZWOU1uvU-rcY_fJ",
  },
  {
    id: 7,
    title: "El despertar de la Fuerza",
    longTitle: "Star Wars: Episodio VII - El despertar de la Fuerza",
    releaseDate: "18-12-2015",
    description:
      "Treinta años después de la destrucción de la segunda Estrella de la Muerte, la siniestra Primera Orden, comandada por el misterioso Snoke y su aprendiz Kylo Ren, surge de las cenizas del Imperio. La Resistencia, liderada por la General Leia Organa, intenta frustrar la amenaza de la Primera Orden, pero están desesperados por ayuda. Rey, una chatarrera del desierto, y Finn, un ex soldado de asalto, se encuentran uniendo fuerzas con Han Solo y Chewbacca en una misión desesperada para devolver un droide de la unidad BB con un mapa que lleva a Luke Skywalker de vuelta a la Resistencia.",
    directedBy: "J.J. Abrams",
    writtenBy: ["Lawrence Kasdan", "Michael Arndt", "J.J. Abrams"],
    era: "Ascenso de la Primera Orden",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 16min",
    trailer: "https://www.youtube.com/embed/V8qlIZsutAQ?si=RAzwgEWqER-ghZcG",
  },
  {
    id: 8,
    title: "Rogue One",
    longTitle: "Rogue One: una historia de Star Wars",
    releaseDate: "16-12-2016",
    description:
      'Desde Lucasfilm llega la primera de las películas independientes de Star Wars, "Rogue One: Una Historia de Star Wars", una nueva y épica aventura. En un tiempo de conflicto, un grupo de héroes improbables se unen en una misión para robar los planos de la Estrella de la Muerte, el arma definitiva de destrucción del Imperio. Este evento clave en la línea temporal de Star Wars reúne a personas comunes que eligen hacer cosas extraordinarias y, al hacerlo, se convierten en parte de algo más grande que ellos mismos.',
    directedBy: "Gareth Edwards",
    writtenBy: ["Chris Weitz", "Tony Gilroy"],
    era: "Reinado del Imperio",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 14min",
    trailer: "https://www.youtube.com/embed/Xcs4OpUJWrM?si=597F4YbuRsPr1SNr",
  },
  {
    id: 9,
    title: "Los últimos Jedi",
    longTitle: "Star Wars: Episodio VIII - Los últimos Jedi",
    releaseDate: "13-12-2017",
    description:
      "La Resistencia está desesperadamente necesitada de ayuda cuando se ven perseguidos de manera imposible por la Primera Orden. Mientras Rey viaja a un remoto planeta llamado Ahch-To para reclutar a Luke Skywalker para la Resistencia, Finn y Rose, una mecánica, emprenden su propia misión con la esperanza de ayudar a la Resistencia a escapar finalmente de la Primera Orden. Pero todos se encuentran en el planeta de sal de Crait para una última batalla.",
    directedBy: "Rian Johnson",
    writtenBy: ["Rian Johnson"],
    era: "Ascenso de la Primera Orden",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 32min",
    trailer: "https://www.youtube.com/embed/anOJjqQb8x0?si=Uer37aHiR7V-ksrZ",
  },
  {
    id: 10,
    title: "Han Solo",
    longTitle: "Han Solo: una historia de Star Wars",
    releaseDate: "23-05-2018",
    description:
      'Aborda el Halcón Milenario y viaja a una galaxia muy, muy lejana en "Solo: Una Historia de Star Wars", una nueva aventura con el más querido canalla de la galaxia. A través de una serie de atrevidas escapadas en lo más profundo de un oscuro y peligroso inframundo criminal, Han Solo conoce a su poderoso futuro copiloto Chewbacca y se encuentra con el famoso jugador Lando Calrissian, en un viaje que marcará el rumbo de uno de los héroes más improbables de la saga de Star Wars.',
    directedBy: "Ron Howard",
    writtenBy: ["Lawrence Kasdan", "Jon Kasdan"],
    era: "Reinado del Imperio",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG",
    runtime: "2h 15min",
    trailer: "https://www.youtube.com/embed/C-YZiAXcbY8?si=ziNqNFHYrvIqYO4h",
  },
  {
    id: 11,
    title: "El ascenso de Skywalker",
    longTitle: "Star Wars: Episodio IX - El ascenso de Skywalker",
    releaseDate: "18-12-2019",
    description:
      "Lucasfilm y el director J.J. Abrams se unen una vez más para llevar a los espectadores en un viaje épico a una galaxia muy, muy lejana con Star Wars: El Ascenso de Skywalker, la emocionante conclusión de la emblemática saga Skywalker, en la que nacerán nuevas leyendas y la batalla final por la libertad aún está por venir.",
    directedBy: "J.J. Abrams",
    writtenBy: [
      "Derek Connolly",
      "Colin Trevorrow",
      "Chris Terrio",
      "J.J. Abrams",
    ],
    era: "Ascenso de la Primera Orden",
    genres: ["Acción", "Aventura", "Fantasía", "Ciencia Ficción"],
    rating: "PG-13",
    runtime: "2h 22min",
    trailer: "https://www.youtube.com/embed/AXRAdmJvzcs?si=LsJXWAlYoF853LpY",
  },
];

export const movieById = (id: number): DetailMovie | undefined =>
  movies.find((movie) => movie.id === id);
